language: ruby
services:
  - postgresql
before_install:
  - nvm install --lts
before_script:
  - yarn
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
